
package testmart.business;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import testmart.webservice.ObjectFactory;
import testmart.webservice.Product;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatalog", targetNamespace = "http://webservice.testmart/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalog {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<testmart.webservice.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductsV2", targetNamespace = "http://webservice.testmart/", className = "testmart.webservice.GetProductsV2")
    @ResponseWrapper(localName = "getProductsV2Response", targetNamespace = "http://webservice.testmart/", className = "testmart.webservice.GetProductsV2Response")
    @Action(input = "http://webservice.testmart/ProductCatalog/getProductsV2Request", output = "http://webservice.testmart/ProductCatalog/getProductsV2Response")
    public List<Product> getProductsV2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "fetch_catagories")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchCatagories", targetNamespace = "http://webservice.testmart/", className = "testmart.webservice.FetchCatagories")
    @ResponseWrapper(localName = "fetchCatagoriesResponse", targetNamespace = "http://webservice.testmart/", className = "testmart.webservice.FetchCatagoriesResponse")
    @Action(input = "fetch_catagories", output = "http://webservice.testmart/ProductCatalog/fetchCatagoriesResponse")
    public List<String> fetchCatagories();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://webservice.testmart/", className = "testmart.webservice.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://webservice.testmart/", className = "testmart.webservice.GetProductsResponse")
    @Action(input = "http://webservice.testmart/ProductCatalog/getProductsRequest", output = "http://webservice.testmart/ProductCatalog/getProductsResponse")
    public List<String> getProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://webservice.testmart/", className = "testmart.webservice.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://webservice.testmart/", className = "testmart.webservice.AddProductResponse")
    @Action(input = "http://webservice.testmart/ProductCatalog/addProductRequest", output = "http://webservice.testmart/ProductCatalog/addProductResponse")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
