
package testmart.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShopInfo", targetNamespace = "http://webservice.testmart/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ShopInfo {


    /**
     * 
     * @param lookupInput
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "lookupResult", partName = "lookupResult")
    @Action(input = "http://webservice.testmart/ShopInfo/getShopInfoRequest", output = "http://webservice.testmart/ShopInfo/getShopInfoResponse")
    public String getShopInfo(
        @WebParam(name = "lookupInput", partName = "lookupInput")
        String lookupInput);

}
